### ISSUE TITLE
combined left and right LiDAR data  

### ISSUE THREAD

**Issue by og-lee** [qiank10/MVDNet#3]
Thank you for sharing ORR dataset labels.
I have some questions about the lidar preparation part. I ran the prepare_lidar_data.py and got the combined lidar data. 
When the car is moving the left and right lidar mismatch a little at the centerline of the car like the pictures at the bottom. 
Where is this mismatching coming from? I would also like to know if I could align this. 
Thank you. 

<img width="388" alt="seperated" src="https://user-images.githubusercontent.com/78589530/124705188-370daf00-df30-11eb-9049-7ad7479f1b54.PNG">

<img width="366" alt="before_seperated" src="https://user-images.githubusercontent.com/78589530/124705192-383edc00-df30-11eb-8bd0-f534f4f36a70.PNG">

**Comment by qiank10** [comment]
Hi, it is because the lidar point clouds are aligned with the radar intensity map. The scanning period of the radar is 0.25s, during which the radar beam starts from the front direction, scans 360 degrees clockwise, and ends again in the front direction. So the aligned lidar points at 359deg are 0.25s later than those at 1deg. During this time lag, the ego vehicle may move forward, so there is an interrupt along the front direction and it is more obvious when a vehicle crosses the front direction. 

You can rotate this interrupt to other directions, but it still distorts point clouds in those directions. You can also add two more frames of lidar point clouds prior to and after the scanning period of the radar to complete the objects at the interrupt, but it introduces duplicate images of these objects.

**Comment by og-lee** [comment]
Thank you qiank for your kind answer. It helped a lot.
